name: Daily Script

on:
  schedule:
    # - cron: '0 5 40 * *'  # 每天 UTC 00:00 执行
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run script
        run: node ./dist/main.js
